version: '3.8'

services:
  playread:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playread
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - /tmp/playwright-mcp-output:/tmp/playwright-mcp-output
    networks:
      - default

networks:
  default:
    name: playread-network
