[build]
cmd = "npm install"

[start]
cmd = "npx playwright install --with-deps chromium && npm run http"

[nix]
pkgs = ["nodejs_22", "npm"]

nixpkgsVersion = "unstable"

[env]
PORT = "3000"
PLAYWRIGHT_HEADLESS = "true"
