[build]
cmd = "npm install"

[start]
cmd = "npm run http"

[nix]
pkgs = [
  "nodejs_22",
  "npm",
  "chromium",
  "libxkbcommon",
  "libxss",
  "libappindicator-gtk3",
  "libgconf-2-4",
  "libnotify",
  "libnss3",
  "libgbm",
  "libdrm",
  "mesa"
]

nixpkgsVersion = "unstable"

[env]
PORT = "3000"
PLAYWRIGHT_HEADLESS = "true"
CHROMIUM_BIN = "/run/current-system/sw/bin/chromium"
