[build]
cmd = "npm install && npx playwright install --with-deps"

[start]
cmd = "npm run http"

[nix]
pkgs = [
  "nodejs_22",
  "npm",
  "chromium",
  "libxkbcommon",
  "libxss",
  "libappindicator-gtk3",
  "libgconf-2-4",
  "libnotify",
  "libnss3",
  "libgbm",
  "libdrm",
  "mesa"
]

nixpkgsVersion = "unstable"

[env]
PORT = "3000"
PLAYWRIGHT_HEADLESS = "true"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "0"
