[build]
cmd = "npm install && npx playwright install chromium"

[start]
cmd = "npm run http"

[nix]
pkgs = ["nodejs_22", "npm"]

nixpkgsVersion = "unstable"

[env]
PORT = "3000"
PLAYWRIGHT_HEADLESS = "true"
